### ISSUE TITLE
avue 2.9.5

### ISSUE THREAD

**Issue by bestAndbest** [nmxiaowei/avue#564]
查询列表和搜索有时候会报这个错，但是后端数据有正常响应，很奇怪的bug
TypeError: Cannot read properties of undefined (reading 'key')
    at ir (vue.min.js:6:41857)
    at vue.min.js:6:59678
    at x (vue.min.js:6:59842)
    at vue.min.js:6:59365
    at x (vue.min.js:6:59842)
    at a.__patch__ (vue.min.js:6:60979)
    at a.e._update (vue.min.js:6:34519)
    at a.r (vue.min.js:6:68168)
    at fn.get (vue.min.js:6:26768)
    at fn.run (vue.min.js:6:27652)

**Comment by nmxiaowei** [comment]
key主键没设置 默认位id rowKey配置属性
