### ISSUE TITLE
500 | Internal Server Error

### ISSUE THREAD

**Issue by ghost** [nmxiaowei/avue#6]
```
...
vue-ssr-server-bundle.json  838 kB          [emitted]  [big]
server started at localhost:8080
error during render : /
ReferenceError: window is not defined
    at Object.<anonymous> (src/mock/menu.js:75:15)
    at __webpack_require__ (webpack:/webpack/bootstrap 886ec991fabfc0442bcd:25:0)
    at Object.module.exports.DIC.SEX.label (server-bundle.js:6442:69)
    at __webpack_require__ (webpack:/webpack/bootstrap 886ec991fabfc0442bcd:25:0)
    at Object.module.exports.module.exports (server-bundle.js:7221:68)
    at __webpack_require__ (webpack:/webpack/bootstrap 886ec991fabfc0442bcd:25:0)
    at Object.<anonymous> (server-bundle.js:734:72)
    at __webpack_require__ (webpack:/webpack/bootstrap 886ec991fabfc0442bcd:25:0)
    at Object.<anonymous> (server-bundle.js:2048:65)
    at __webpack_require__ (webpack:/webpack/bootstrap 886ec991fabfc0442bcd:25:0)
error during render : /favicon.ico
```

![image](https://user-images.githubusercontent.com/19482459/38232158-63d3f0dc-3748-11e8-808d-c00201ff2f3d.png)

I am getting this error after I ran `npm start`.

> $ node -v
> v8.10.0

**Comment by hyungryuk** [comment]
@xdrone2008   Can you attach webpack config file as well?

**Comment by nmxiaowei** [comment]
Thank you for feedback and follow up the problem as soon as possible
