### ISSUE TITLE
希望avue补充下文档说明

### ISSUE THREAD

**Issue by wuxiaolan91** [nmxiaowei/avue#613]
我开了一个新项目
- node 16.19
- vue 2.6.14
- axios: 1.4.0
- avue：2.10.12

这是我的main.js
```
import Vue from "vue";
import App from "./App.vue";
import Avue from "@smallwei/avue";
// import AVUE from "@/assets/js/avue.js";
import axios from "axios";
// let Avue = window.Avue;
Vue.config.productionTip = false;
console.log("vue");
console.log(Vue);
console.log("avue");
console.log(Avue);
Vue.use(Avue, { axios });
new Vue({
  render: (h) => h(App),
}).$mount("#app");
```
然后页面上就会报错
```
Uncaught runtime errors:
×
ERROR
this.$refs.form.clearValidate is not a function
TypeError: this.$refs.form.clearValidate is not a function
    at VueComponent.clearValidate (webpack-internal:///./node_modules/@smallwei/avue/lib/avue.min.js:8049:29)
    at eval (webpack-internal:///./node_modules/@smallwei/avue/lib/avue.min.js:7914:36)
```
我反复卸载安装这个avue包都还是这样
我把avue的源代码down下来，发现是具体这里报错
```
    // 验证表单是否显隐
    vaildDisplay: function vaildDisplay(column) {
      var key;
      if (!this.validatenull(column.display)) {
        key = 'display';
      } else if (this.isAdd) {
        key = 'addDisplay';
      } else if (this.isEdit) {
        key = 'editDisplay';
      } else if (this.isView) {
        key = 'viewDisplay';
      }
      return this.vaildData(column[key], true);
    },
    clearValidate: function clearValidate(list) {
      this.$refs.form.clearValidate(list); // 这句话报错
```
this和this.$refs,this.$refs.form都是有值的，clearvalidate这个方法是element的方法

我是因为看avue的文档说自己是基于element的，然后我也看到avue官方文档有写说要
import axios
我没看到还要引用element，既然这样，那我还以为是不是avue自己去引用了。
对于我这种第一次用avue的人来说，我觉得文档可以更有好点
在安装章节：https://avuejs.com/docs/installation/
里增加说明：明确用户必须先引用element的模块和它的css

这样咱们的文档就更棒啦~

我在搜avue的时候看到知乎上一些人觉得avue文档不够清晰，
我觉得咱们作为开源软件能做成这样已经给大家提供了很多便利
就是如果能文档更清晰一些就更赞啦
辛苦所有的avue开源程序员为我们做的贡献。

**Comment by wuxiaolan91** [comment]
我也可以自己来补充这里的文档说明，并在自己的使用中看看是否还有哪里还有需要完善的文档~
你们code review和merge就好~

这是我之前参与的开源项目[fks](https://github.com/JacksonTian/fks)

**Comment by nmxiaowei** [comment]
感谢支持，我们会逐步完善这部分文档，同时也欢迎code review
https://gitee.com/smallweigit/avue-doc
